name: "Terraform"

on:
  push:
    branches:
      - master
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform.yaml'
      - '.github/workflows/terraform_apply.yaml'

jobs:
  terraform_apply:
    defaults:
      run:
        working-directory: ./terraform
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform Init
        id: init
        run: terraform init
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        env:
          TF_VAR_github_token: ${{ secrets.TF_VAR_GITHUB_TOKEN }}
      - name: Terraform Apply
        env:
          TF_VAR_github_token: ${{ secrets.TF_VAR_GITHUB_TOKEN }}
        run: terraform apply -auto-approve
